
// AUTH Action Types

export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_REGISTER_SUCCESS = 'AUTR_RIGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTR_RIGISTER_FAILURE';

export const AUTH_LOGIN_FAILURE = 'AUTR_LOGIN_FAILURE';
export const AUTH_LOGIN_SUCCESS = 'AUTR_LOGIN_SUCCESS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';


// BOARD Action Types

export const BOARD_INIT = "BOARD_INIT";

export const BOARD_GET_SUCCESS = "BOARD_GET_SUCCESS";
export const BOARD_GET_FAILURE = "BOARD_GET_FAILURE";

export const BOARD_SCROLL_GET = "BOARD_SCROLL_GET";
export const BOARD_SCROLL_GET_SUCCESS = "BOARD_SCROLL_GET_SUCCESS";
export const BOARD_SCROLL_GET_FAILURE = "BOARD_SCROLL_GET_FAILURE";

export const BOARD_DETAIL_GET_SUCCESS = "BOARD_DETAIL_GET_SUCCESS";
export const BOARD_DETAIL_GET_FAILURE = "BOARD_DETAIL_GET_FAILURE";

// STRUCTURE Action Types

export const STRUCTURE_SEARCH_BAR_ON = "STRUCTURE_SEARCH_BAR_ON";
export const STRUCTURE_SEARCH_BAR_OFF = "STRUCTURE_SEARCH_BAR_OFF";

export const STRUCTURE_HEADER_ON = "STRUCTURE_HEADER_ON";
export const STRUCTURE_HEADER_OFF = "STRUCTURE_HEADER_OFF";

export const STRUCTURE_CATEGORY_ON = "STRUCTURE_CATEGORY_ON";
export const STRUCTURE_CATEGORY_OFF = "STRUCTURE_CATEGORY_OFF";


// TOPIC Action Types

export const TOPIC_HOME = 'TOPIC_HOME';
export const TOPIC_MARKET = "TOPIC_MARKET";
export const TOPIC_CARPOOL = 'TOPIC_CARPOOL';
export const TOPIC_NETWORKING = "TOPIC_NETWORKING";